In [1]:
import torch

# define my model
class Model(torch.nn.Module):
    def __init__(self, hidden_size_common,out_classes):
        super(Model, self).__init__()
        self.conv_1 = torch.nn.Conv2d(1,32,3,1,1)
        self.conv_2 = torch.nn.Conv2d(32,128,3,1,1)
        # self.conv_3 = torch.nn.Conv2d(64,128,3,1,1)

        
        self.flatten = torch.nn.Flatten()


        self.linear_in = torch.nn.Linear(128*5, hidden_size_common)
        self.linear_hidden = torch.nn.Linear(hidden_size_common, hidden_size_common)
        self.linear_out = torch.nn.Linear(hidden_size_common, out_classes)
        self.ReLU = torch.nn.ReLU()
        self.Activate = torch.nn.Tanh()
    
    def forward(self, x):
        
        out = self.conv_1(x)
        # out = self.pool(out)
        out = self.conv_2(out)
        # out = self.conv_3(out)
        # out = self.pool(out)

        out = self.flatten(out)

        out = self.linear_in(out)
        
        out = self.Activate(out)
        for _ in range(4):
            out = self.linear_hidden(out)
            out = self.ReLU(out)
        out = self.linear_out(out)
        out = self.ReLU(out)
        return out


e:\Anaconda\envs\python38\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import pandas as pd
import numpy as np
Test_Data = pd.read_csv("Test_Data.csv").values
ver_feature = torch.tensor(Test_Data[:,2:7], dtype=torch.float32)
ver_feature = ver_feature.view(-1, 1,1,5)
print(ver_feature)
ver_label = Test_Data[:,7:8]
print(ver_label)

tensor([[[[14.6000,  5.3000, 17.0000, 42.0000, 16.0000]]],


        [[[15.0000,  5.7000, 23.8000, 34.0000, 24.6000]]],


        [[[18.9000,  8.6000, 38.5000, 35.0000, 23.0000]]],


        [[[18.2000,  8.5000, 27.0000, 45.0000, 33.0000]]],


        [[[19.6000,  9.0000, 26.4000, 39.0000, 37.8000]]],


        [[[16.0000,  9.5000, 18.0000, 63.0000, 14.0000]]],


        [[[17.0000,  7.2000, 34.0000, 56.0000, 43.5000]]]])
[[0.6495]
 [0.9338]
 [1.53  ]
 [0.77  ]
 [0.8504]
 [0.5862]
 [0.6776]]


In [3]:
# Model_Parameter/Deep_Slope_model_states(4096__4__2Conv2d(32,128,3,1,1)__0.0109).pt

In [4]:
# 加载模型  
model_finish_path = 'Deep_Slope_model_states(4096__4__2Conv2d(32,128,3,1,1)__0.0109).pt'
state_dict = torch.load(model_finish_path)
# create my model
model = Model(4096, 1)
model.load_state_dict(state_dict=state_dict)
# 模型预测

score = model(ver_feature)
print(score)
print(ver_label)
for i in range(len(ver_label)):
    err = score[i].item() - ver_label[i][0]
    print(f'{err:.4f}')

tensor([[0.6502],
        [0.9355],
        [1.5510],
        [0.7732],
        [0.8547],
        [0.6049],
        [0.6707]], grad_fn=<ReluBackward0>)
[[0.6495]
 [0.9338]
 [1.53  ]
 [0.77  ]
 [0.8504]
 [0.5862]
 [0.6776]]
0.0007
0.0017
0.0210
0.0032
0.0043
0.0187
-0.0069
